import { test } from "node:test";
import assert from "node:assert/strict";
import { layout, renderSvg, getPreset, parseYaml } from "../dist/index.js";
import { readFileSync } from "node:fs";

const example = parseYaml(readFileSync(new URL("../examples/prisma-review.yaml", import.meta.url), "utf8"));
const preset = getPreset("prisma-2020");

test("layout produces all preset nodes", () => {
  const d = layout(example, preset);
  assert.equal(d.nodes.length, preset.nodes.length);
  for (const n of preset.nodes) {
    assert.ok(d.nodes.find((x) => x.id === n.id), `missing node ${n.id}`);
  }
});

test("layout produces all preset edges with valid points", () => {
  const d = layout(example, preset);
  assert.equal(d.edges.length, preset.edges.length);
  for (const e of d.edges) {
    assert.ok(e.points.length >= 2, `edge ${e.from}->${e.to} too few points`);
    for (const p of e.points) {
      assert.ok(Number.isFinite(p.x), `edge ${e.from}->${e.to} non-finite x`);
      assert.ok(Number.isFinite(p.y), `edge ${e.from}->${e.to} non-finite y`);
    }
  }
});

test("nodes have positive width and height", () => {
  const d = layout(example, preset);
  for (const n of d.nodes) {
    assert.ok(n.width > 0, `node ${n.id} width <= 0`);
    assert.ok(n.height > 0, `node ${n.id} height <= 0`);
  }
});

test("nodes do not overlap horizontally within a row", () => {
  const d = layout(example, preset);
  // Group by approximate y-band.
  const byY = new Map();
  for (const n of d.nodes) {
    const key = Math.round(n.y);
    const arr = byY.get(key) ?? [];
    arr.push(n);
    byY.set(key, arr);
  }
  for (const [y, group] of byY) {
    group.sort((a, b) => a.x - b.x);
    for (let i = 1; i < group.length; i++) {
      const a = group[i - 1];
      const b = group[i];
      assert.ok(a.x + a.width <= b.x + 1, `nodes ${a.id} and ${b.id} overlap at y=${y}`);
    }
  }
});

test("layout is deterministic (same input → same output)", () => {
  const a = layout(example, preset);
  const b = layout(example, preset);
  assert.deepEqual(b, a);
});

test("s/n edge into wide colSpan target drops a straight vertical", () => {
  // PRISMA's `included` box has colSpan 3, so its top edge spans every
  // column. The arrow from `reports_assessed` (col 0) into `included`
  // must therefore be a single vertical segment, not an L-bend that
  // would otherwise carve through `reports_other_excluded` at row 5.
  const d = layout(example, preset);
  const edge = d.edges.find((e) => e.from === "reports_assessed" && e.to === "included");
  assert.ok(edge, "expected reports_assessed → included edge");
  assert.equal(edge.points.length, 2, "expected exactly two points (straight drop)");
  const [a, b] = edge.points;
  assert.equal(a.x, b.x, "endpoints share x — vertical line");
  assert.ok(a.y < b.y, "edge goes downward");

  // And so should the right-track main flow into the same wide box.
  const right = d.edges.find((e) => e.from === "reports_other_assessed" && e.to === "included");
  assert.ok(right, "expected reports_other_assessed → included edge");
  assert.equal(right.points.length, 2);
  assert.equal(right.points[0].x, right.points[1].x);
});

test("renderSvg produces parseable XML with correct dimensions", () => {
  const d = layout(example, preset);
  const svg = renderSvg(d, { generatedAt: "2026-04-25T00:00:00Z" });
  assert.ok(svg.startsWith("<?xml"));
  assert.ok(svg.includes(`width="${d.width}"`));
  assert.ok(svg.includes(`height="${d.height}"`));
  assert.ok(svg.includes("</svg>"));
});

test("renderSvg embeds DOI metadata when present", () => {
  const d = layout(example, preset);
  const svg = renderSvg(d, { generatedAt: "2026-04-25T00:00:00Z" });
  assert.ok(svg.includes("doi:10.0000/example.2026.001"));
});

test("renderSvg with embedMetadata=false omits metadata block", () => {
  const d = layout(example, preset);
  const svg = renderSvg(d, { embedMetadata: false });
  assert.ok(!svg.includes("<metadata>"));
});

test("renderSvg with watermark=false omits watermark text", () => {
  const d = layout(example, preset);
  const svg = renderSvg(d, { watermark: false });
  assert.ok(!svg.includes("Generated by FlowDoc"));
});

test("rendered SVG is bytewise-deterministic when generatedAt is fixed", () => {
  const d = layout(example, preset);
  const a = renderSvg(d, { generatedAt: "2026-04-25T00:00:00Z" });
  const b = renderSvg(d, { generatedAt: "2026-04-25T00:00:00Z" });
  assert.equal(a, b);
});
