/**
 * Deterministic PDF 1.4 exporter.
 *
 * Walks the laid-out diagram and emits a single-page PDF that mirrors the
 * SVG output (rectangles, polylines, arrow heads, multi-line centered text).
 * Uses the Base14 Helvetica family — no font embedding required, and
 * everything past the header is deterministic given the same diagram.
 *
 * PDF coordinate origin is bottom-left; SVG is top-left. We flip y at draw
 * time so absolute coordinates remain consistent with the SVG renderer.
 *
 * Limitations: ASCII / WinAnsi only (covers PRISMA / CONSORT / STROBE
 * labels). CJK glyphs would need a Type 0 composite font and embedded
 * CIDFont — outside the scope of v0.1.
 */

import type { LaidOutDiagram, LaidOutNode, LaidOutEdge, LaidOutSection } from "../core/types.js";

export interface PdfOptions {
  /** Override creation timestamp for byte-deterministic output. */
  generatedAt?: string;
  /** Add the FlowDoc watermark in the bottom-right. Default true. */
  watermark?: boolean;
}

export function toPdf(d: LaidOutDiagram, opts: PdfOptions = {}): Uint8Array {
  const watermark = opts.watermark !== false;
  const ts = opts.generatedAt ?? new Date().toISOString();

  const W = d.width;
  const H = d.height;

  const ops: string[] = [];

  // White background.
  ops.push(`q`, `1 1 1 rg`, `0 0 ${num(W)} ${num(H)} re`, `f`, `Q`);

  // Sections (light fill, no stroke, drawn first behind nodes).
  for (const s of d.sections) {
    ops.push(`q`, rgb("0.953 0.965 0.984"), rect(s.x, s.y, s.width, s.height, H), `f`, `Q`);
  }

  // Section labels (rotated -90° around centre).
  for (const s of d.sections) drawSectionLabel(ops, s, H);

  // Edges.
  for (const e of d.edges) drawEdge(ops, e, H);

  // Nodes.
  for (const n of d.nodes) drawNode(ops, n, H);

  // Watermark — bottom-right of the SVG, which maps to y=6 in PDF space.
  if (watermark) {
    const wm = `Generated by FlowDoc · preset ${d.preset.id}@${d.preset.version}`;
    const fontSize = 9;
    const wmWidth = textWidth(wm, fontSize, false);
    ops.push(
      `q`,
      rgb("0.604 0.627 0.651"),
      `BT`,
      `/F1 ${num(fontSize)} Tf`,
      `${num(W - 8 - wmWidth)} 6 Td`,
      `(${escPdfString(wm)}) Tj`,
      `ET`,
      `Q`,
    );
  }

  const contents = ops.join("\n") + "\n";

  // Build object table.
  const objects: string[] = [];
  // 1: Catalog
  objects.push("<< /Type /Catalog /Pages 2 0 R >>");
  // 2: Pages
  objects.push("<< /Type /Pages /Kids [3 0 R] /Count 1 >>");
  // 3: Page
  objects.push(
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${num(W)} ${num(H)}] ` +
      `/Resources << /Font << /F1 4 0 R /F2 5 0 R >> /ProcSet [/PDF /Text] >> ` +
      `/Contents 6 0 R >>`,
  );
  // 4: Font Helvetica
  objects.push(
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",
  );
  // 5: Font Helvetica-Bold
  objects.push(
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>",
  );
  // 6: Contents
  objects.push(
    `<< /Length ${contents.length} >>\nstream\n${contents}endstream`,
  );
  // 7: Info dict
  objects.push(
    `<< /Title (${escPdfString(d.metadata?.title ?? "")}) ` +
      `/Producer (FlowDoc) ` +
      `/Creator (FlowDoc) ` +
      `/CreationDate (${pdfDate(ts)}) ` +
      `/ModDate (${pdfDate(ts)}) >>`,
  );

  // Header + body.
  let body = "%PDF-1.4\n%âãÏÓ\n";
  const offsets: number[] = [0];
  for (let i = 0; i < objects.length; i++) {
    offsets.push(byteLength(body));
    body += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`;
  }

  const xrefOffset = byteLength(body);
  let xref = `xref\n0 ${objects.length + 1}\n`;
  xref += `0000000000 65535 f \n`;
  for (let i = 1; i <= objects.length; i++) {
    xref += `${pad10(offsets[i]!)} 00000 n \n`;
  }

  const trailer =
    `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R /Info 7 0 R ` +
    `/ID [<${idHex(ts)}><${idHex(ts)}>] >>\n` +
    `startxref\n${xrefOffset}\n%%EOF\n`;

  return latin1Bytes(body + xref + trailer);
}

/* --------------------------- drawing helpers --------------------------- */

function drawNode(ops: string[], n: LaidOutNode, H: number): void {
  const s = n.style;
  const fill = hexToPdfRgb(s.fill);
  const stroke = hexToPdfRgb(s.stroke);
  const text = hexToPdfRgb(s.textColor);

  ops.push(`q`);
  // Fill
  ops.push(rgb(fill), rect(n.x, n.y, n.width, n.height, H), `f`);
  // Stroke (with optional dashed pattern)
  if (s.dashed) ops.push(`[4 3] 0 d`);
  ops.push(rgbStroke(stroke), `1.2 w`, rect(n.x, n.y, n.width, n.height, H), `S`);
  if (s.dashed) ops.push(`[] 0 d`);
  // Text — multi-line centred
  ops.push(rgb(text));
  drawCenteredText(ops, n.text, n.x, n.y, n.width, n.height, s.fontSize, s.bold, H);
  ops.push(`Q`);
}

function drawEdge(ops: string[], e: LaidOutEdge, H: number): void {
  if (e.points.length < 2) return;
  ops.push(`q`, rgbStroke("0.133 0.133 0.133"), `1.3 w`);
  const [first, ...rest] = e.points;
  ops.push(`${num(first!.x)} ${num(H - first!.y)} m`);
  for (const p of rest) ops.push(`${num(p.x)} ${num(H - p.y)} l`);
  ops.push(`S`);
  if (e.arrow) {
    const last = e.points[e.points.length - 1]!;
    const prev = e.points[e.points.length - 2]!;
    drawArrowHead(ops, prev, last, H);
  }
  ops.push(`Q`);
  if (e.label) {
    const mid = midpoint(e.points);
    ops.push(`q`, rgb("0.267 0.267 0.267"), `BT`);
    const w = textWidth(e.label, 10, false);
    ops.push(`/F1 10 Tf`, `${num(mid.x - w / 2)} ${num(H - (mid.y - 4))} Td`, `(${escPdfString(e.label)}) Tj`, `ET`, `Q`);
  }
}

function drawArrowHead(
  ops: string[],
  from: { x: number; y: number },
  to: { x: number; y: number },
  H: number,
): void {
  const size = 8;
  // Direction in PDF coords (flip y).
  const fx = from.x;
  const fy = H - from.y;
  const tx = to.x;
  const ty = H - to.y;
  const dx = tx - fx;
  const dy = ty - fy;
  const len = Math.sqrt(dx * dx + dy * dy) || 1;
  const ux = dx / len;
  const uy = dy / len;
  // Triangle: tip = (tx,ty); base centre = tip - size*u; base half-width = size/2 perpendicular to u.
  const bx = tx - size * ux;
  const by = ty - size * uy;
  const px = -uy;
  const py = ux;
  const halfW = size / 2;
  const p1x = bx + px * halfW;
  const p1y = by + py * halfW;
  const p2x = bx - px * halfW;
  const p2y = by - py * halfW;
  ops.push(
    rgb("0.133 0.133 0.133"),
    `${num(tx)} ${num(ty)} m`,
    `${num(p1x)} ${num(p1y)} l`,
    `${num(p2x)} ${num(p2y)} l`,
    `h`,
    `f`,
  );
}

function drawSectionLabel(ops: string[], s: LaidOutSection, H: number): void {
  const cx = s.x + s.width / 2;
  const cy = s.y + s.height / 2;
  // Rotate -90° around the centre of the section label area, then draw
  // text centred at (cx,cy). Using a cm matrix.
  const fontSize = 13;
  const w = textWidth(s.label, fontSize, true);
  const ascent = fontSize * 0.74;
  // Translation in PDF space (flip cy).
  const px = cx;
  const py = H - cy;
  ops.push(`q`, rgb("0.216 0.278 0.353"));
  // Rotate -90 around (px,py): cm = [cos sin -sin cos tx ty]
  // For -90°: cos=0, sin=-1 → matrix 0 -1 1 0 px py (translate first then rotate).
  // Compose: T(px,py) * R(-90) = matrix [0 -1 1 0 px py].
  ops.push(`0 -1 1 0 ${num(px)} ${num(py)} cm`);
  ops.push(`BT`, `/F2 ${num(fontSize)} Tf`, `${num(-w / 2)} ${num(-ascent / 2)} Td`, `(${escPdfString(s.label)}) Tj`, `ET`);
  ops.push(`Q`);
}

function drawCenteredText(
  ops: string[],
  text: string,
  x: number,
  y: number,
  width: number,
  height: number,
  fontSize: number,
  bold: boolean,
  H: number,
): void {
  const lines = text.split("\n");
  const lineHeight = Math.round(fontSize * 1.25);
  const totalH = lines.length * lineHeight;
  const startY = y + (height - totalH) / 2 + fontSize;
  const fontRef = bold ? "/F2" : "/F1";
  ops.push(`BT`, `${fontRef} ${num(fontSize)} Tf`);
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i] ?? "";
    if (line.length === 0) continue;
    const w = textWidth(line, fontSize, bold);
    const tx = x + (width - w) / 2;
    const ty = H - (startY + i * lineHeight);
    ops.push(`1 0 0 1 ${num(tx)} ${num(ty)} Tm`, `(${escPdfString(line)}) Tj`);
  }
  ops.push(`ET`);
}

/* ----------------------------- primitives ----------------------------- */

function rect(x: number, y: number, w: number, h: number, H: number): string {
  // PDF rect with origin at bottom-left; we flip y.
  return `${num(x)} ${num(H - y - h)} ${num(w)} ${num(h)} re`;
}

function rgb(color: string): string {
  return `${color} rg`;
}

function rgbStroke(color: string): string {
  return `${color} RG`;
}

function num(n: number): string {
  // Trim to 3 decimal places, strip trailing zeros.
  const s = n.toFixed(3);
  return s.replace(/(\.\d*?)0+$/, "$1").replace(/\.$/, "");
}

function midpoint(pts: Array<{ x: number; y: number }>): { x: number; y: number } {
  if (pts.length < 2) return pts[0]!;
  const mid = Math.floor(pts.length / 2);
  if (pts.length % 2 === 1) return pts[mid]!;
  return { x: (pts[mid - 1]!.x + pts[mid]!.x) / 2, y: (pts[mid - 1]!.y + pts[mid]!.y) / 2 };
}

function hexToPdfRgb(hex: string): string {
  // Accept "#rrggbb" or "#rgb" or named "none"; default to black.
  if (hex === "none" || !hex) return "0 0 0";
  let h = hex.startsWith("#") ? hex.slice(1) : hex;
  if (h.length === 3) h = h.split("").map((c) => c + c).join("");
  if (h.length !== 6) return "0 0 0";
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  return `${num(r)} ${num(g)} ${num(b)}`;
}

/**
 * Approximate Helvetica advance widths (per em / 1000), keyed by char code.
 * Values for codes 32-126 sourced from Adobe's published Base14 metrics
 * (Helvetica.afm). Anything outside that range falls back to the average.
 */
const HELV_WIDTHS: Record<number, number> = {
  32: 278, 33: 278, 34: 355, 35: 556, 36: 556, 37: 889, 38: 667, 39: 191,
  40: 333, 41: 333, 42: 389, 43: 584, 44: 278, 45: 333, 46: 278, 47: 278,
  48: 556, 49: 556, 50: 556, 51: 556, 52: 556, 53: 556, 54: 556, 55: 556,
  56: 556, 57: 556, 58: 278, 59: 278, 60: 584, 61: 584, 62: 584, 63: 556,
  64: 1015, 65: 667, 66: 667, 67: 722, 68: 722, 69: 667, 70: 611, 71: 778,
  72: 722, 73: 278, 74: 500, 75: 667, 76: 556, 77: 833, 78: 722, 79: 778,
  80: 667, 81: 778, 82: 722, 83: 667, 84: 611, 85: 722, 86: 667, 87: 944,
  88: 667, 89: 667, 90: 611, 91: 278, 92: 278, 93: 278, 94: 469, 95: 556,
  96: 222, 97: 556, 98: 556, 99: 500, 100: 556, 101: 556, 102: 278, 103: 556,
  104: 556, 105: 222, 106: 222, 107: 500, 108: 222, 109: 833, 110: 556, 111: 556,
  112: 556, 113: 556, 114: 333, 115: 500, 116: 278, 117: 556, 118: 500, 119: 722,
  120: 500, 121: 500, 122: 500, 123: 334, 124: 260, 125: 334, 126: 584,
};
const HELV_BOLD_WIDTHS: Record<number, number> = {
  // Helvetica-Bold widths differ slightly; we approximate with +6% over regular.
};

function textWidth(s: string, fontSize: number, bold: boolean): number {
  let total = 0;
  for (const ch of s) {
    const code = ch.codePointAt(0) ?? 0;
    let w = HELV_WIDTHS[code];
    if (w === undefined) w = 556; // generic fallback
    if (bold) {
      const bw = HELV_BOLD_WIDTHS[code];
      w = bw ?? Math.round(w * 1.06);
    }
    total += w;
  }
  return (total / 1000) * fontSize;
}

/* ----------------------------- encoding ----------------------------- */

/**
 * Unicode → WinAnsi mapping for the codepoints that appear in WinAnsi but
 * sit in the Latin-1 supplement / general-punctuation Unicode blocks.
 * Covers the punctuation we actually emit in PRISMA / CONSORT / STROBE
 * templates (bullet, en/em dash, smart quotes, ellipsis, …).
 */
const WIN_ANSI_REMAP: Record<number, number> = {
  0x20ac: 0x80, // €
  0x201a: 0x82, // ‚
  0x0192: 0x83, // ƒ
  0x201e: 0x84, // „
  0x2026: 0x85, // …
  0x2020: 0x86, // †
  0x2021: 0x87, // ‡
  0x02c6: 0x88, // ˆ
  0x2030: 0x89, // ‰
  0x0160: 0x8a, // Š
  0x2039: 0x8b, // ‹
  0x0152: 0x8c, // Œ
  0x017d: 0x8e, // Ž
  0x2018: 0x91, // '
  0x2019: 0x92, // '
  0x201c: 0x93, // "
  0x201d: 0x94, // "
  0x2022: 0x95, // •
  0x2013: 0x96, // –
  0x2014: 0x97, // —
  0x02dc: 0x98, // ˜
  0x2122: 0x99, // ™
  0x0161: 0x9a, // š
  0x203a: 0x9b, // ›
  0x0153: 0x9c, // œ
  0x017e: 0x9e, // ž
  0x0178: 0x9f, // Ÿ
};

function escPdfString(s: string): string {
  let out = "";
  for (const ch of s) {
    let code = ch.codePointAt(0) ?? 0;
    const remap = WIN_ANSI_REMAP[code];
    if (remap !== undefined) code = remap;
    if (code === 0x28 || code === 0x29 || code === 0x5c) {
      out += "\\" + String.fromCharCode(code);
    } else if (code === 0x0a) {
      out += "\\n";
    } else if (code === 0x0d) {
      out += "\\r";
    } else if (code >= 0x20 && code <= 0x7e) {
      out += String.fromCharCode(code);
    } else if (code <= 0xff) {
      // WinAnsi / Latin-1 fallthrough.
      out += String.fromCharCode(code);
    } else {
      out += "?"; // beyond WinAnsi — see file-header comment.
    }
  }
  return out;
}

function pdfDate(iso: string): string {
  // ISO 8601 → PDF date "D:YYYYMMDDHHmmSSZ".
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "D:19700101000000Z";
  const yyyy = d.getUTCFullYear().toString().padStart(4, "0");
  const mm = (d.getUTCMonth() + 1).toString().padStart(2, "0");
  const dd = d.getUTCDate().toString().padStart(2, "0");
  const hh = d.getUTCHours().toString().padStart(2, "0");
  const mi = d.getUTCMinutes().toString().padStart(2, "0");
  const ss = d.getUTCSeconds().toString().padStart(2, "0");
  return `D:${yyyy}${mm}${dd}${hh}${mi}${ss}Z`;
}

function idHex(seed: string): string {
  // Deterministic 16-byte ID derived from seed; not cryptographic.
  let h1 = 0x811c9dc5;
  let h2 = 0xdeadbeef;
  for (let i = 0; i < seed.length; i++) {
    const c = seed.charCodeAt(i);
    h1 = Math.imul(h1 ^ c, 16777619) >>> 0;
    h2 = Math.imul(h2 ^ c, 2246822519) >>> 0;
  }
  const a = h1.toString(16).padStart(8, "0");
  const b = h2.toString(16).padStart(8, "0");
  return (a + b + a + b).slice(0, 32);
}

function pad10(n: number): string {
  return n.toString().padStart(10, "0");
}

function byteLength(s: string): number {
  // We only emit Latin-1 chars in the body; codepoints map 1:1 to bytes.
  return s.length;
}

function latin1Bytes(s: string): Uint8Array {
  const out = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i) & 0xff;
  return out;
}
