/**
 * Deterministic PNG exporter.
 *
 * Walks the laid-out diagram and rasterises into an RGB framebuffer:
 * sections, edges (Manhattan polylines + filled triangle arrow heads),
 * node rectangles (filled + stroked, optional dashed pattern), and
 * multi-line centred text using the embedded 5x7 ASCII bitmap font.
 *
 * The PNG itself is built from scratch using IHDR / IDAT / IEND chunks
 * and Node's `zlib.deflateSync` for the IDAT compression. No external
 * dependency. Output is byte-deterministic for the same diagram.
 *
 * Limitations: ASCII labels only — non-ASCII codepoints become a small
 * filled-square placeholder. Section labels are rendered horizontally
 * (rather than rotated -90°) for simplicity; the PDF and SVG outputs
 * still show the rotated form.
 */

import { deflateSync, constants as zlibConsts } from "node:zlib";
import type {
  LaidOutDiagram,
  LaidOutNode,
  LaidOutEdge,
  LaidOutSection,
  NodeStyle,
} from "../core/types.js";
import { GLYPH_HEIGHT, GLYPH_WIDTH, glyphFor, pxWidth } from "./font5x7.js";

export interface PngOptions {
  /** Background colour, default "#ffffff". */
  background?: string;
  /** Add the FlowDoc watermark. Default true. */
  watermark?: boolean;
}

interface RGB { r: number; g: number; b: number }

export function toPng(d: LaidOutDiagram, opts: PngOptions = {}): Uint8Array {
  const W = Math.ceil(d.width);
  const H = Math.ceil(d.height);
  const watermark = opts.watermark !== false;

  // RGB framebuffer, row-major.
  const fb = new Uint8Array(W * H * 3);

  // Background.
  fillBg(fb, W, H, parseColor(opts.background ?? "#ffffff"));

  // Sections (light fill, drawn first behind nodes).
  for (const s of d.sections) drawSection(fb, W, H, s);

  // Edges with arrow heads.
  for (const e of d.edges) drawEdge(fb, W, H, e);

  // Nodes.
  for (const n of d.nodes) drawNode(fb, W, H, n);

  // Watermark.
  if (watermark) {
    const wm = `Generated by FlowDoc | preset ${d.preset.id}@${d.preset.version}`;
    drawText(fb, W, H, wm, 0, 0, GREY, /*scale*/ 1, /*bold*/ false, {
      anchor: "right",
      baseline: "bottom",
      x: W - 6,
      y: H - 4,
    });
  }

  return encodePng(fb, W, H);
}

/* ------------------------- drawing primitives -------------------------- */

function fillBg(fb: Uint8Array, W: number, H: number, c: RGB): void {
  for (let i = 0; i < W * H; i++) {
    fb[i * 3] = c.r;
    fb[i * 3 + 1] = c.g;
    fb[i * 3 + 2] = c.b;
  }
}

function setPixel(fb: Uint8Array, W: number, H: number, x: number, y: number, c: RGB): void {
  if (x < 0 || y < 0 || x >= W || y >= H) return;
  const i = (y * W + x) * 3;
  fb[i] = c.r;
  fb[i + 1] = c.g;
  fb[i + 2] = c.b;
}

function fillRect(fb: Uint8Array, W: number, H: number, x: number, y: number, w: number, h: number, c: RGB): void {
  const x0 = Math.max(0, Math.floor(x));
  const y0 = Math.max(0, Math.floor(y));
  const x1 = Math.min(W, Math.ceil(x + w));
  const y1 = Math.min(H, Math.ceil(y + h));
  for (let yy = y0; yy < y1; yy++) {
    for (let xx = x0; xx < x1; xx++) {
      const i = (yy * W + xx) * 3;
      fb[i] = c.r;
      fb[i + 1] = c.g;
      fb[i + 2] = c.b;
    }
  }
}

function strokeRect(
  fb: Uint8Array, W: number, H: number,
  x: number, y: number, w: number, h: number,
  c: RGB, dashed: boolean,
): void {
  const x0 = Math.round(x);
  const y0 = Math.round(y);
  const x1 = Math.round(x + w) - 1;
  const y1 = Math.round(y + h) - 1;
  // top
  hLine(fb, W, H, x0, x1, y0, c, dashed);
  // bottom
  hLine(fb, W, H, x0, x1, y1, c, dashed);
  // left
  vLine(fb, W, H, x0, y0, y1, c, dashed);
  // right
  vLine(fb, W, H, x1, y0, y1, c, dashed);
}

function hLine(fb: Uint8Array, W: number, H: number, x0: number, x1: number, y: number, c: RGB, dashed: boolean): void {
  const a = Math.min(x0, x1);
  const b = Math.max(x0, x1);
  for (let x = a; x <= b; x++) {
    if (dashed && Math.floor((x - a) / 4) % 2 === 1) continue;
    setPixel(fb, W, H, x, y, c);
  }
}
function vLine(fb: Uint8Array, W: number, H: number, x: number, y0: number, y1: number, c: RGB, dashed: boolean): void {
  const a = Math.min(y0, y1);
  const b = Math.max(y0, y1);
  for (let y = a; y <= b; y++) {
    if (dashed && Math.floor((y - a) / 4) % 2 === 1) continue;
    setPixel(fb, W, H, x, y, c);
  }
}

function drawLine(fb: Uint8Array, W: number, H: number, x0: number, y0: number, x1: number, y1: number, c: RGB): void {
  // Bresenham (covers diagonals from arrow-head edges as well as stray cases).
  let x = Math.round(x0);
  let y = Math.round(y0);
  const xe = Math.round(x1);
  const ye = Math.round(y1);
  const dx = Math.abs(xe - x);
  const dy = -Math.abs(ye - y);
  const sx = x < xe ? 1 : -1;
  const sy = y < ye ? 1 : -1;
  let err = dx + dy;
  for (;;) {
    setPixel(fb, W, H, x, y, c);
    if (x === xe && y === ye) break;
    const e2 = 2 * err;
    if (e2 >= dy) { err += dy; x += sx; }
    if (e2 <= dx) { err += dx; y += sy; }
  }
}

function fillTriangle(
  fb: Uint8Array, W: number, H: number,
  ax: number, ay: number, bx: number, by: number, cx: number, cy: number,
  col: RGB,
): void {
  const minX = Math.max(0, Math.floor(Math.min(ax, bx, cx)));
  const minY = Math.max(0, Math.floor(Math.min(ay, by, cy)));
  const maxX = Math.min(W - 1, Math.ceil(Math.max(ax, bx, cx)));
  const maxY = Math.min(H - 1, Math.ceil(Math.max(ay, by, cy)));
  // Edge function — barycentric inside-test.
  const edge = (x1: number, y1: number, x2: number, y2: number, x: number, y: number) =>
    (x - x1) * (y2 - y1) - (y - y1) * (x2 - x1);
  for (let y = minY; y <= maxY; y++) {
    for (let x = minX; x <= maxX; x++) {
      const w0 = edge(bx, by, cx, cy, x + 0.5, y + 0.5);
      const w1 = edge(cx, cy, ax, ay, x + 0.5, y + 0.5);
      const w2 = edge(ax, ay, bx, by, x + 0.5, y + 0.5);
      if ((w0 >= 0 && w1 >= 0 && w2 >= 0) || (w0 <= 0 && w1 <= 0 && w2 <= 0)) {
        setPixel(fb, W, H, x, y, col);
      }
    }
  }
}

/* ----------------------------- text ----------------------------- */

interface TextOpts {
  anchor?: "left" | "centre" | "right";
  baseline?: "top" | "middle" | "bottom";
  /** Optional override anchor x/y; otherwise the function args are top-left. */
  x?: number;
  y?: number;
}

function drawText(
  fb: Uint8Array, W: number, H: number,
  text: string, x: number, y: number,
  c: RGB, scale: number, _bold: boolean, opts: TextOpts = {},
): void {
  if (text.length === 0) return;
  const w = pxWidth(text, scale);
  const h = GLYPH_HEIGHT * scale;
  let ax = opts.x ?? x;
  let ay = opts.y ?? y;
  if (opts.anchor === "centre") ax -= w / 2;
  else if (opts.anchor === "right") ax -= w;
  if (opts.baseline === "middle") ay -= h / 2;
  else if (opts.baseline === "bottom") ay -= h;
  ax = Math.round(ax);
  ay = Math.round(ay);

  for (let i = 0; i < text.length; i++) {
    const ch = text[i]!;
    const g = glyphFor(ch);
    for (let col = 0; col < GLYPH_WIDTH; col++) {
      const colByte = g[col]!;
      for (let row = 0; row < GLYPH_HEIGHT; row++) {
        if ((colByte >> row) & 1) {
          fillRect(fb, W, H, ax + col * scale, ay + row * scale, scale, scale, c);
        }
      }
    }
    ax += GLYPH_WIDTH * scale + scale; // advance by glyph + 1px gap (scaled)
  }
}

function fontScale(_svgFontSize: number): number {
  // The 5x7 GLCD glyph has a ~0.5-em advance (5 col + 1 col gap = 6 / 12 ≈ 0.5)
  // which is just under Helvetica's 0.56 em used by the layout's pre-wrap.
  // At scale=1 the bitmap text fits inside every box the layout reserved;
  // bumping to scale=2 doubles the advance and pushes labels outside their
  // boxes. Trade-off: text is small (7 px tall) but always legible and never
  // overflows. SVG / PDF remain the high-fidelity outputs.
  return 1;
}

/* -------------------------- diagram drawing -------------------------- */

function drawSection(fb: Uint8Array, W: number, H: number, s: LaidOutSection): void {
  fillRect(fb, W, H, s.x, s.y, s.width, s.height, SECTION_FILL);
  // Section label rotated -90° around the centre of the strip — matches
  // the SVG/PDF outputs (text reads bottom-to-top, first char at bottom).
  const scale = fontScale(13);
  const cx = s.x + s.width / 2;
  const cy = s.y + s.height / 2;
  drawTextRotated(fb, W, H, s.label, cx, cy, SECTION_LABEL, scale);
}

/**
 * Render `text` rotated -90° (counterclockwise on screen) around (cx, cy).
 *
 * SVG `transform="rotate(-90, cx, cy)"` makes left-to-right horizontal text
 * read bottom-to-top vertically, with the first character at the bottom.
 * We replicate that here so PNG section labels match SVG/PDF.
 */
function drawTextRotated(
  fb: Uint8Array, W: number, H: number,
  text: string, cx: number, cy: number,
  c: RGB, scale: number,
): void {
  if (!text) return;
  const advance = (GLYPH_WIDTH + 1) * scale;
  const glyphHeight = GLYPH_HEIGHT * scale;
  const totalLen = text.length * advance - scale; // last glyph has no trailing gap

  for (let i = 0; i < text.length; i++) {
    const g = glyphFor(text[i]!);
    for (let col = 0; col < GLYPH_WIDTH; col++) {
      const colByte = g[col]!;
      for (let row = 0; row < GLYPH_HEIGHT; row++) {
        if (((colByte >> row) & 1) === 0) continue;
        // Pixel offset from rotated-string centre, in pre-rotation coords.
        const ox = i * advance + col * scale - totalLen / 2;
        const oy = row * scale - glyphHeight / 2;
        // SVG -90° rotation in screen coords: (ox, oy) → (oy, -ox).
        const sx = cx + oy;
        const sy = cy - ox;
        fillRect(fb, W, H, sx, sy, scale, scale, c);
      }
    }
  }
}

function drawEdge(fb: Uint8Array, W: number, H: number, e: LaidOutEdge): void {
  const pts = e.points;
  if (pts.length < 2) return;
  for (let i = 1; i < pts.length; i++) {
    const a = pts[i - 1]!;
    const b = pts[i]!;
    drawLine(fb, W, H, a.x, a.y, b.x, b.y, EDGE);
  }
  if (e.arrow) {
    const last = pts[pts.length - 1]!;
    const prev = pts[pts.length - 2]!;
    drawArrow(fb, W, H, prev, last);
  }
  if (e.label) {
    const mid = midpoint(pts);
    drawText(fb, W, H, e.label, 0, 0, EDGE_LABEL, 1, false, {
      anchor: "centre",
      baseline: "bottom",
      x: mid.x,
      y: mid.y - 2,
    });
  }
}

function drawArrow(fb: Uint8Array, W: number, H: number, from: { x: number; y: number }, to: { x: number; y: number }): void {
  const size = 8;
  const dx = to.x - from.x;
  const dy = to.y - from.y;
  const len = Math.sqrt(dx * dx + dy * dy) || 1;
  const ux = dx / len;
  const uy = dy / len;
  const bx = to.x - size * ux;
  const by = to.y - size * uy;
  const px = -uy;
  const py = ux;
  const half = size / 2;
  fillTriangle(
    fb, W, H,
    to.x, to.y,
    bx + px * half, by + py * half,
    bx - px * half, by - py * half,
    EDGE,
  );
}

function drawNode(fb: Uint8Array, W: number, H: number, n: LaidOutNode): void {
  const s = n.style;
  fillRect(fb, W, H, n.x, n.y, n.width, n.height, parseColor(s.fill));
  strokeRect(fb, W, H, n.x, n.y, n.width, n.height, parseColor(s.stroke), s.dashed);

  // Multi-line centred text.
  const lines = n.text.split("\n");
  const scale = fontScale(s.fontSize);
  const lineHeight = GLYPH_HEIGHT * scale + 3 * scale;
  const totalH = lines.length * lineHeight;
  const startY = n.y + (n.height - totalH) / 2;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i] ?? "";
    if (!line) continue;
    drawText(fb, W, H, line, 0, 0, parseColor(s.textColor), scale, s.bold, {
      anchor: "centre",
      baseline: "top",
      x: n.x + n.width / 2,
      y: startY + i * lineHeight,
    });
  }
}

/* ------------------------- colours & helpers ------------------------- */

const EDGE: RGB = { r: 0x22, g: 0x22, b: 0x22 };
const EDGE_LABEL: RGB = { r: 0x44, g: 0x44, b: 0x44 };
const GREY: RGB = { r: 0x9a, g: 0xa0, b: 0xa6 };
const SECTION_FILL: RGB = { r: 0xf3, g: 0xf6, b: 0xfb };
const SECTION_LABEL: RGB = { r: 0x37, g: 0x47, b: 0x5a };

function parseColor(hex: string): RGB {
  if (!hex || hex === "none") return { r: 0, g: 0, b: 0 };
  let h = hex.startsWith("#") ? hex.slice(1) : hex;
  if (h.length === 3) h = h.split("").map((c) => c + c).join("");
  if (h.length !== 6) return { r: 0, g: 0, b: 0 };
  return {
    r: parseInt(h.slice(0, 2), 16),
    g: parseInt(h.slice(2, 4), 16),
    b: parseInt(h.slice(4, 6), 16),
  };
}

function midpoint(pts: Array<{ x: number; y: number }>): { x: number; y: number } {
  if (pts.length < 2) return pts[0]!;
  const mid = Math.floor(pts.length / 2);
  if (pts.length % 2 === 1) return pts[mid]!;
  return { x: (pts[mid - 1]!.x + pts[mid]!.x) / 2, y: (pts[mid - 1]!.y + pts[mid]!.y) / 2 };
}

/* ------------------------- PNG file format ------------------------- */

const PNG_SIGNATURE = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

function encodePng(fb: Uint8Array, W: number, H: number): Uint8Array {
  // Build raw scanlines: 1 filter byte (0 = None) + RGB row.
  const rowLen = W * 3;
  const raw = new Uint8Array((rowLen + 1) * H);
  for (let y = 0; y < H; y++) {
    const dst = y * (rowLen + 1);
    raw[dst] = 0; // filter = None
    raw.set(fb.subarray(y * rowLen, (y + 1) * rowLen), dst + 1);
  }

  const compressed = deflateSync(raw, { level: zlibConsts.Z_DEFAULT_COMPRESSION });

  const chunks: Uint8Array[] = [PNG_SIGNATURE];
  // IHDR
  const ihdr = new Uint8Array(13);
  writeUint32BE(ihdr, 0, W);
  writeUint32BE(ihdr, 4, H);
  ihdr[8] = 8;  // bit depth
  ihdr[9] = 2;  // color type: truecolor (RGB)
  ihdr[10] = 0; // compression
  ihdr[11] = 0; // filter
  ihdr[12] = 0; // interlace
  chunks.push(makeChunk("IHDR", ihdr));
  // IDAT
  chunks.push(makeChunk("IDAT", new Uint8Array(compressed)));
  // IEND
  chunks.push(makeChunk("IEND", new Uint8Array(0)));

  return concatBuffers(chunks);
}

function makeChunk(type: string, data: Uint8Array): Uint8Array {
  const out = new Uint8Array(8 + data.length + 4);
  writeUint32BE(out, 0, data.length);
  for (let i = 0; i < 4; i++) out[4 + i] = type.charCodeAt(i);
  out.set(data, 8);
  const crcData = out.subarray(4, 8 + data.length);
  writeUint32BE(out, 8 + data.length, crc32(crcData));
  return out;
}

function writeUint32BE(buf: Uint8Array, offset: number, val: number): void {
  buf[offset] = (val >>> 24) & 0xff;
  buf[offset + 1] = (val >>> 16) & 0xff;
  buf[offset + 2] = (val >>> 8) & 0xff;
  buf[offset + 3] = val & 0xff;
}

function concatBuffers(parts: Uint8Array[]): Uint8Array {
  let total = 0;
  for (const p of parts) total += p.length;
  const out = new Uint8Array(total);
  let off = 0;
  for (const p of parts) {
    out.set(p, off);
    off += p.length;
  }
  return out;
}

const CRC_TABLE: Uint32Array = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

function crc32(buf: Uint8Array): number {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) {
    c = CRC_TABLE[(c ^ buf[i]!) & 0xff]! ^ (c >>> 8);
  }
  return (c ^ 0xffffffff) >>> 0;
}
