import type { LaidOutDiagram, LaidOutNode, LaidOutEdge, LaidOutSection, NodeStyle } from "./types.js";

const ARROW_SIZE = 8;

export interface SvgOptions {
  /** Embed source metadata (DOI, preset) as RDF in <metadata>. Default true. */
  embedMetadata?: boolean;
  /** Background color. Default "#ffffff". Use "none" for transparent. */
  background?: string;
  /** Add the FlowDoc watermark in the bottom-right. Default true. */
  watermark?: boolean;
  /** Override generated-at timestamp (for reproducible output). */
  generatedAt?: string;
}

export function renderSvg(d: LaidOutDiagram, opts: SvgOptions = {}): string {
  const bg = opts.background ?? "#ffffff";
  const embedMetadata = opts.embedMetadata !== false;
  const watermark = opts.watermark !== false;

  const parts: string[] = [];
  parts.push(
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" ` +
      `version="1.1" ` +
      `width="${d.width}" height="${d.height}" viewBox="0 0 ${d.width} ${d.height}" ` +
      `font-family="Helvetica, Arial, 'Noto Sans', 'PingFang TC', sans-serif">`,
  );

  if (embedMetadata) parts.push(metadataBlock(d, opts.generatedAt));

  parts.push(defsBlock());

  if (bg !== "none") {
    parts.push(`<rect x="0" y="0" width="${d.width}" height="${d.height}" fill="${bg}"/>`);
  }

  // Sections (drawn first, behind nodes).
  for (const s of d.sections) parts.push(renderSection(s));

  // Edges.
  for (const e of d.edges) parts.push(renderEdge(e));

  // Nodes.
  for (const n of d.nodes) parts.push(renderNode(n));

  // Watermark.
  if (watermark) {
    const wm = `Generated by FlowDoc · preset ${d.preset.id}@${d.preset.version}`;
    parts.push(
      `<text x="${d.width - 8}" y="${d.height - 6}" ` +
        `font-size="9" fill="#9aa0a6" text-anchor="end">${escapeXml(wm)}</text>`,
    );
  }

  parts.push(`</svg>`);
  return parts.join("\n");
}

function defsBlock(): string {
  return (
    `<defs>` +
    `<marker id="arrow" viewBox="0 0 ${ARROW_SIZE} ${ARROW_SIZE}" refX="${ARROW_SIZE - 1}" refY="${ARROW_SIZE / 2}" ` +
    `markerWidth="${ARROW_SIZE}" markerHeight="${ARROW_SIZE}" orient="auto-start-reverse">` +
    `<path d="M0,0 L${ARROW_SIZE},${ARROW_SIZE / 2} L0,${ARROW_SIZE} Z" fill="#222222"/>` +
    `</marker>` +
    `</defs>`
  );
}

function metadataBlock(d: LaidOutDiagram, ts?: string): string {
  const md = d.metadata;
  const generated = ts ?? new Date().toISOString();
  const rdf =
    `<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" ` +
    `xmlns:dc="http://purl.org/dc/elements/1.1/" ` +
    `xmlns:flowdoc="https://flowdoc.dev/ns#">` +
    `<rdf:Description>` +
    (md?.title ? `<dc:title>${escapeXml(md.title)}</dc:title>` : "") +
    (md?.doi ? `<dc:identifier>doi:${escapeXml(md.doi)}</dc:identifier>` : "") +
    (md?.authors?.length
      ? `<dc:creator>${escapeXml(md.authors.join("; "))}</dc:creator>`
      : "") +
    `<flowdoc:preset>${escapeXml(d.preset.id)}@${escapeXml(d.preset.version)}</flowdoc:preset>` +
    `<flowdoc:generatedAt>${generated}</flowdoc:generatedAt>` +
    `</rdf:Description>` +
    `</rdf:RDF>`;
  return `<metadata>${rdf}</metadata>`;
}

function renderSection(s: LaidOutSection): string {
  return (
    `<g class="section">` +
    `<rect x="${s.x}" y="${s.y}" width="${s.width}" height="${s.height}" ` +
    `fill="#f3f6fb" stroke="none" rx="4" ry="4"/>` +
    `<text x="${s.x + s.width / 2}" y="${s.y + s.height / 2}" ` +
    `transform="rotate(-90, ${s.x + s.width / 2}, ${s.y + s.height / 2})" ` +
    `text-anchor="middle" dominant-baseline="middle" ` +
    `font-size="13" font-weight="700" fill="#37475a">${escapeXml(s.label)}</text>` +
    `</g>`
  );
}

function renderEdge(e: LaidOutEdge): string {
  const d = e.points.map((p, i) => `${i === 0 ? "M" : "L"} ${p.x} ${p.y}`).join(" ");
  const marker = e.arrow ? ` marker-end="url(#arrow)"` : "";
  let out = `<path d="${d}" fill="none" stroke="#222222" stroke-width="1.3"${marker}/>`;
  if (e.label) {
    const mid = midpoint(e.points);
    out +=
      `<text x="${mid.x}" y="${mid.y - 4}" font-size="10" fill="#444" text-anchor="middle">` +
      `${escapeXml(e.label)}</text>`;
  }
  return out;
}

function midpoint(pts: Array<{ x: number; y: number }>): { x: number; y: number } {
  if (pts.length < 2) return pts[0]!;
  const mid = Math.floor(pts.length / 2);
  if (pts.length % 2 === 1) return pts[mid]!;
  return { x: (pts[mid - 1]!.x + pts[mid]!.x) / 2, y: (pts[mid - 1]!.y + pts[mid]!.y) / 2 };
}

function renderNode(n: LaidOutNode): string {
  const s = n.style;
  const rx = s.rounded ? 8 : 2;
  const strokeDasharray = s.dashed ? ` stroke-dasharray="4 3"` : "";
  const fontWeight = s.bold ? ` font-weight="700"` : "";

  const lines = n.text.split("\n");
  const lineHeight = Math.round(s.fontSize * 1.25);
  const totalTextHeight = lines.length * lineHeight;
  const startY = n.y + (n.height - totalTextHeight) / 2 + s.fontSize;

  const tspans = lines
    .map(
      (ln, i) =>
        `<tspan x="${n.x + n.width / 2}" y="${startY + i * lineHeight}">${escapeXml(ln || " ")}</tspan>`,
    )
    .join("");

  return (
    `<g class="node" data-id="${escapeXml(n.id)}">` +
    `<rect x="${n.x}" y="${n.y}" width="${n.width}" height="${n.height}" ` +
    `rx="${rx}" ry="${rx}" fill="${s.fill}" stroke="${s.stroke}" stroke-width="1.2"${strokeDasharray}/>` +
    `<text text-anchor="middle" fill="${s.textColor}" font-size="${s.fontSize}"${fontWeight}>` +
    tspans +
    `</text>` +
    `</g>`
  );
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
